site_name: ProtonType Docs
site_description: 'Framework typescript para desenvolvimentos de APIs REST'
site_author: 'Humberto Machado'
copyright: 'Copyright (c) 2017 Humberto Machado'
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'reds'
markdown_extensions:
  - codehilite
repo_url: https://github.com/protontype/protontype
repo_name: protontype/protontype
edit_uri: 'https://github.com/protontype/protontype-docs/blob/master/docs'
pages:
- Home: 'index.md'
- User Guide:
    - 'Quick Start': 'quickstart.md'
    - Database:
        - 'Connectors': "db-connector.md"
        - 'Models': 'models-typeorm.md'
    - Routers: 
        - 'Router': 'router.md'
        - 'CRUD Router': basecrudrouter.md
    - 'Middleware': 'middlewares.md'
    - 'Configurações': 'config.md'
    - 'Iniciando Aplicação': 'bootstrap.md'
- License: 'license.md'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/linck'
    - type: 'twitter'
      link: 'https://twitter.com/betolinck'
