site_name: ProtonType Docs
site_description: 'Framework typescript para desenvolvimentos de APIs REST'
site_author: 'Humberto Machado'
copyright: 'Copyright (c) 2017 Humberto Machado'
theme: 'material'
markdown_extensions:
  - codehilite
repo_url: https://github.com/linck/protontype
repo_name: linck/protontype

pages:
- Home: 'index.md'
- User Guide:
    - 'Quick Start': 'quickstart.md'
    - Routers: 
        - 'Router': 'router.md'
        - 'BaseCrudRouter': basecrudrouter.md
    - Middewares: 
        - 'Middleware': 'middlewares.md'
        - 'Middleware de Autenticação': 'authmiddleware.md'
    - 'Models': 'models.md'
    - 'Configurações': 'config.md'
    - 'Iniciando Aplicação': 'bootstrap.md'
- License: 'license.md'

extra:
  palette:
    primary: 'teal'
    accent: 'teal'
  social:
    - type: 'github'
      link: 'https://github.com/linck'
    - type: 'twitter'
      link: 'https://twitter.com/betolinck'
